f = open('split Nirvana.txt')
name_song = f.readline()
text_song = f.read()
print('Название песни:', name_song)
print('Текст песни:')
print(text_song)
# ff = open('сплошной Тургенев.txt')
# turgenev = ff.read()
# print(turgenev)
print('Символов в строке:', len(text_song))
print('первый символ:', text_song[0])
print('последний символ(ввод или пробел):', text_song[-1])
number_hello = text_song.count('hello')
number_Hello = text_song.count('Hello')
print('hello:', number_hello + number_Hello)
text_song = text_song.replace('hello', 'hi')
print(text_song)
